/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteRouteImport } from './routes/_bookings/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as BookingsBookingsRouteImport } from './routes/_bookings/bookings'
import { Route as BookingsMyBookingsRouteImport } from './routes/_bookings/my-bookings'
import { Route as BookingsNotificationsRouteImport } from './routes/_bookings/notifications'
import { Route as BookingsSettingsRouteImport } from './routes/_bookings/settings'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as BookingsBookingsBookingIdRouteImport } from './routes/_bookings/bookings_.$bookingId'
import { Route as BookingsRoomsRoomIdRouteImport } from './routes/_bookings/rooms.$roomId'
import { Route as AdminRoomsRoomIdRouteImport } from './routes/admin/rooms_.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRouteRoute = BookingsRouteRouteImport.update({
  id: '/_bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingsRoute = BookingsBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BookingsRouteRoute,
} as any)
const BookingsMyBookingsRoute = BookingsMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => BookingsRouteRoute,
} as any)
const BookingsNotificationsRoute = BookingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BookingsRouteRoute,
} as any)
const BookingsSettingsRoute = BookingsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BookingsRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BookingsBookingsBookingIdRoute =
  BookingsBookingsBookingIdRouteImport.update({
    id: '/bookings_/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => BookingsRouteRoute,
  } as any)
const BookingsRoomsRoomIdRoute = BookingsRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => BookingsRouteRoute,
} as any)
const AdminRoomsRoomIdRoute = AdminRoomsRoomIdRouteImport.update({
  id: '/rooms_/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/bookings': typeof BookingsBookingsRoute
  '/my-bookings': typeof BookingsMyBookingsRoute
  '/notifications': typeof BookingsNotificationsRoute
  '/settings': typeof BookingsSettingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/$bookingId': typeof BookingsBookingsBookingIdRoute
  '/rooms/$roomId': typeof BookingsRoomsRoomIdRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/bookings': typeof BookingsBookingsRoute
  '/my-bookings': typeof BookingsMyBookingsRoute
  '/notifications': typeof BookingsNotificationsRoute
  '/settings': typeof BookingsSettingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/bookings/$bookingId': typeof BookingsBookingsBookingIdRoute
  '/rooms/$roomId': typeof BookingsRoomsRoomIdRoute
  '/admin/rooms/$roomId': typeof AdminRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_bookings': typeof BookingsRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_bookings/bookings': typeof BookingsBookingsRoute
  '/_bookings/my-bookings': typeof BookingsMyBookingsRoute
  '/_bookings/notifications': typeof BookingsNotificationsRoute
  '/_bookings/settings': typeof BookingsSettingsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/_bookings/bookings_/$bookingId': typeof BookingsBookingsBookingIdRoute
  '/_bookings/rooms/$roomId': typeof BookingsRoomsRoomIdRoute
  '/admin/rooms_/$roomId': typeof AdminRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/bookings'
    | '/my-bookings'
    | '/notifications'
    | '/settings'
    | '/admin/bookings'
    | '/admin/rooms'
    | '/admin/users'
    | '/admin/'
    | '/bookings/$bookingId'
    | '/rooms/$roomId'
    | '/admin/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/bookings'
    | '/my-bookings'
    | '/notifications'
    | '/settings'
    | '/admin/bookings'
    | '/admin/rooms'
    | '/admin/users'
    | '/admin'
    | '/bookings/$bookingId'
    | '/rooms/$roomId'
    | '/admin/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_bookings'
    | '/admin'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_bookings/bookings'
    | '/_bookings/my-bookings'
    | '/_bookings/notifications'
    | '/_bookings/settings'
    | '/admin/bookings'
    | '/admin/rooms'
    | '/admin/users'
    | '/admin/'
    | '/_bookings/bookings_/$bookingId'
    | '/_bookings/rooms/$roomId'
    | '/admin/rooms_/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRouteRoute: typeof BookingsRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_bookings': {
      id: '/_bookings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BookingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_bookings/bookings': {
      id: '/_bookings/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsBookingsRouteImport
      parentRoute: typeof BookingsRouteRoute
    }
    '/_bookings/my-bookings': {
      id: '/_bookings/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof BookingsMyBookingsRouteImport
      parentRoute: typeof BookingsRouteRoute
    }
    '/_bookings/notifications': {
      id: '/_bookings/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof BookingsNotificationsRouteImport
      parentRoute: typeof BookingsRouteRoute
    }
    '/_bookings/settings': {
      id: '/_bookings/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof BookingsSettingsRouteImport
      parentRoute: typeof BookingsRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_bookings/bookings_/$bookingId': {
      id: '/_bookings/bookings_/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingsBookingIdRouteImport
      parentRoute: typeof BookingsRouteRoute
    }
    '/_bookings/rooms/$roomId': {
      id: '/_bookings/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof BookingsRoomsRoomIdRouteImport
      parentRoute: typeof BookingsRouteRoute
    }
    '/admin/rooms_/$roomId': {
      id: '/admin/rooms_/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/admin/rooms/$roomId'
      preLoaderRoute: typeof AdminRoomsRoomIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface BookingsRouteRouteChildren {
  BookingsBookingsRoute: typeof BookingsBookingsRoute
  BookingsMyBookingsRoute: typeof BookingsMyBookingsRoute
  BookingsNotificationsRoute: typeof BookingsNotificationsRoute
  BookingsSettingsRoute: typeof BookingsSettingsRoute
  BookingsBookingsBookingIdRoute: typeof BookingsBookingsBookingIdRoute
  BookingsRoomsRoomIdRoute: typeof BookingsRoomsRoomIdRoute
}

const BookingsRouteRouteChildren: BookingsRouteRouteChildren = {
  BookingsBookingsRoute: BookingsBookingsRoute,
  BookingsMyBookingsRoute: BookingsMyBookingsRoute,
  BookingsNotificationsRoute: BookingsNotificationsRoute,
  BookingsSettingsRoute: BookingsSettingsRoute,
  BookingsBookingsBookingIdRoute: BookingsBookingsBookingIdRoute,
  BookingsRoomsRoomIdRoute: BookingsRoomsRoomIdRoute,
}

const BookingsRouteRouteWithChildren = BookingsRouteRoute._addFileChildren(
  BookingsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRoomsRoomIdRoute: typeof AdminRoomsRoomIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRoomsRoomIdRoute: AdminRoomsRoomIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRouteRoute: BookingsRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
