export const RESET_PASSWORD_TOKEN_EXPIRES_IN_SECONDS = 60 * 60;
export const RESET_PASSWORD_TOKEN_EXPIRES_IN_MINUTES = RESET_PASSWORD_TOKEN_EXPIRES_IN_SECONDS / 60;
export const RESET_PASSWORD_COOLDOWN_SECONDS = 5 * 60;
export const RESET_PASSWORD_COOLDOWN_MS = RESET_PASSWORD_COOLDOWN_SECONDS * 1000;
